---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd
  source:
    repoURL: https://github.com/slavic-viking/oca-argo-cd.git
    targetRevision: main
    path: cicd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: core
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: core
#   source:
#     repoURL: https://github.com/slavic-viking/oca-argo-cd.git
#     targetRevision: main
#     path: core
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: production
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: production
#   source:
#     repoURL: https://github.com/slavic-viking/oca-argo-cd.git
#     targetRevision: cloud
#     path: production
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: production
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: staging
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: staging
#   source:
#     repoURL: https://github.com/slavic-viking/oca-argo-cd.git
#     targetRevision: local
#     path: staging
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: staging
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#     - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: monitoring
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: monitoring
#   source:
#     repoURL: https://github.com/slavic-viking/oca-argo-cd.git
#     targetRevision: cloud
#     path: monitoring
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#     - CreateNamespace=true